### ISSUE TITLE
`template` command for flexible multi-layout

### ISSUE THREAD

**Issue by abey79** [abey79/vpype#183]
New `template` command to generate arbitrary multi-layout based on a config file, e.g.:

![image](https://user-images.githubusercontent.com/49431240/106010240-83b7a900-60b9-11eb-870b-b847a1e2ba86.png)

Config file:
```toml
[template.three4x6]
page_size = "letter"
landscape = false

[[template.three4x6.slot]]
size = ["4in", "6in"]
position = [0, 0]  # slot's top-left corner on page

[[template.three4x6.slot]]
size = ["4in", "6in"]
position = ["4.5in", 0]

[[template.three4x6.slot]]
size = ["4in", "6in"]
position = ["1in", "6.5"]
landscape = true
```
Usage:

```vpype read input.svg [...] template --fit-to-margins 0.5in --landscape three4x6 write output.svg```
